[v1]
"cargo-update 13.0.4 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"diskus 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["diskus"]
"fd-find 8.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["fd"]
"git-delta 0.16.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["delta"]
"hexyl 0.13.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["hexyl"]
"hyperfine 1.17.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hyperfine"]
"temprs 0.5.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "temprs",
    "tp",
]
"thumbs 0.7.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "thumbs",
    "tmux-thumbs",
]
"vivid 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["vivid"]
"zellij-runner 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["zellij-runner"]
